<a href="https://colab.research.google.com/github/stmulugheta/ML-For-Beginners/blob/main/Intro_to_Python_for_data_sceince.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Introduciton to Python for Data Science

In [2]:
a=list(range(1,10))
a[0]=['a', 'b'] # Adding list to the list
print(a)
a=list(range(1,10))
a[0:2]=['a', 'b'] # Adding elenments to the list
print(a)

[['a', 'b'], 2, 3, 4, 5, 6, 7, 8, 9]
['a', 'b', 3, 4, 5, 6, 7, 8, 9]


In [3]:
x=['a', 'b']
print( x+['c','d'] )
print( x+[['c','d']] )

['a', 'b', 'c', 'd']
['a', 'b', ['c', 'd']]


In [6]:
x=['a', 'b']
del(x[-1])
print(x)

['a']


In [5]:
y=['a', 'b']
x=y # copy to a mimorie address 
x=list(y) # or y[:] # to copy the Elenment

In [7]:
# Open the Notebook
# help(help) 

#Open a window in the open part
#?help

In [8]:
x=list(range(5,10))+list(range(1,5))
print(x)
print( sorted(x) )
print( sorted(x, reverse=True) )

[5, 6, 7, 8, 9, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [9]:
# METHODS
my_string='aacd'
print( my_string.replace('d', 'x') )
print( my_string.index('a') )
print( my_string.count('ab') )

my_list=list(my_string) # from string to char
print(my_list)
my_list.reverse()
print(my_list)

aacx
0
0
['a', 'a', 'c', 'd']
['d', 'c', 'a', 'a']


In [13]:
a=list(range(1,5))+[1]
print(a)
print( a.index(1) )

[1, 2, 3, 4, 1]
0


In [14]:
a='abc'
b=a.upper()
print( a + a.upper() + '\n' + str(b) )

abcABC
ABC


# Numpy

In [15]:
import numpy as np

In [16]:
print( np.ones(3) )
print('\n')
print( np.ones(( 1,3)) )
print('\n')
print( np.zeros((3,3)) )
print('\n')
print( np.zeros((3,3,3)) )
print('\n')

[1. 1. 1.]


[[1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]




In [ ]:
print( np.random.randint(low=10, size=(2,2,2)) )
print('\n')
print( np.random.random((2,2)) )
print('\n')
print( np.empty((3,3)))
print('\n')
print( np.full((2,2), 2) )

In [ ]:
print( np.arange(0, 11 , 2) )
print( np.linspace(0, 11, 2) )

In [17]:
x=np.arange(11)
x[::2] #elementi pari

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
x[1::2] #elementi dispari

In [ ]:
x[x>5]

In [ ]:
my_array=np.array([[1,2,3], [4,5,6] ,[7,8,9]], np.int32)
print(my_array)
my_array.shape

In [ ]:
print( my_array[0,:] ) #con le liste non era possibile questa operazione

In [ ]:
#np.sum()
#np.sort()
#np.mean()
#np.median()
#np.std()
#np.corrcoeff()

In [ ]:
a=[0,1,2,3,3,4,4,4,5,5,5,5,6,7,7,8,9]

from matplotlib import pyplot as plt
%matplotlib inline
plt.hist(a)

# Exercises

Create a numpy array with 200 random values between 1 and 100 ( random_list );
Subset random_list by printing out the element at index 50;
Print out a sub-array of random_list that contains the elements at index 100 up to
and including index 110;
Print out a new numpy array with all random_list items whose value is below 25.

In [ ]:
#?np.random.randint

In [ ]:
random_list=np.random.randint(1,101, 200)
print (random_list[50])
print (random_list[100:111])
print( np.array(random_list[random_list<25]))

Create a numpy array with 100 rows and 2 columns, filled with random values
between 1 and 100 ( random_matrix );
Print out the 50th row of random_matrix ;
Store in a new variable second_column the entire second column of
random_matrix ;
Select the value stored in the 25th row, first column of random_matrix and print it
out.

In [ ]:
random_matrix=np.random.randint(1,101, (100,2))
print(random_matrix[49,:])
second_column=random_matrix[:,1]
print(random_matrix[24,0])

* Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.
* Generate an array of length 3n filled with the cyclic pattern 1, 2, 3.
* Create an array of the first 10 odd integers.
* Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.
* Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.
<br> Hint: check out the .zeros() method from NumPy docs!

In [ ]:
#print( np.linspace(-1.3, 2.5, 64) )
n=3
print( np.full((3,n), (1,2,3)) )

print( np.arange(2, 10*2+1, 2) )



# cornice elementi

In [ ]:
z=np.zeros((10,10))
i=np.array([[0,9]])

z[(0,9) , :]=np.ones(10) #z[(0,9) , :]=np.ones((2,10))
z[: , (0,9)]=np.ones((10,2))
print(z)

# elementi diagonale

In [ ]:
A = np.zeros((5, 5))
i = np.arange(5)
A[i, i] = 1.0
print(i)
print(A)

## Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [18]:
a=np.zeros((8,8))
a[1::2, ::2]=1
a[::2, 1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [19]:
a=np.arange(10)
print(a)

a[:8:2]

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6])